version: "3.8"

services:
  infrastructure:
    build: .
    ports:
      - "4000:4000"
    networks:
      - dbs_network
    restart: unless-stopped

networks:
  dbs_network:
    name: startdbs_default
    external: true