version: "3.8"

services:
  infrastructure-gateway:
    build:
      dockerfile: Dockerfile.gateway
    ports:
      - "4000:4000"
    networks:
      - dbs_network
    restart: unless-stopped

  infrastructure-currencies:
    build:
      dockerfile: Dockerfile.currencies
    networks:
      - dbs_network
    restart: unless-stopped

networks:
  dbs_network:
    name: startdbs_default
    external: true