version: "3.8"

services:
  infrastructure-gateway:
    build:
      dockerfile: Dockerfile.gateway
    ports:
      - "4000:4000"
    restart: unless-stopped

  infrastructure-currencies:
    build:
      dockerfile: Dockerfile.currencies
    restart: unless-stopped

  infrastructure-weather:
    build:
      dockerfile: Dockerfile.weather
    restart: unless-stopped
